---
title: "ex11"
author: "Robert A. Stevens"
date: "July 26, 2014"
output: html_document
---

http://learnpythonthehardway.org/book/ex11.html

Exercise 11: Asking Questions

Python code

```{r, engine='python'}
print "How old are you?" # removed "," for Rmd
age = "38" # used instead of "age = raw_input()" for Rmd
print "How tall are you?" # removed "," for Rmd
height = '6\'2\"' # used instead of "height = raw_input()" for Rmd
print "How much do you weigh?" # removed "," for Rmd
weight = "180 lbs" # used instead of "weight = raw_input()" for Rmd

print "So, you're %r old, %r tall and %r heavy." % (
    age, height, weight)
```

R code

```{r, results="hold", collapse=TRUE}
cat("How old are you?")
age <- "38" # used instead of "age <- readline()" for Rmd
cat("How tall are you?")
height <- '6\'2\"' # used instead of "height <- readline()" for Rmd
cat("How much do you weigh?")
weight <- "180 lbs" # used instead of "weight <- readline()" for Rmd

sprintf("So, you're %s old, %s tall and %s heavy.", age, height, weight)
```
