---
title: "ex9"
author: "Robert A. Stevens"
date: "July 25, 2014"
output: html_document
---

http://learnpythonthehardway.org/book/ex9.html

Exercise 9: Printing, Printing, Printing

Python code

```{r, engine='python'}
# Here's some new strange stuff, remember type it exactly.

days = "Mon Tue Wed Thu Fri Sat Sun"
months = "Jan\nFeb\nMar\nApr\nMay\nJun\nJul\nAug"

print "Here are the days: ", days
print "Here are the months: ", months

print """
There's something going on here.
With the three double-quotes.
We'll be able to type as much as we like.
Even 4 lines if we want, or 5, or 6.
"""
```

R code

```{r, results="hold", collapse=TRUE}
# Here's some new strange stuff, remember type it exactly.

days <- "Mon Tue Wed Thu Fri Sat Sun"
months <- "Jan\nFeb\nMar\nApr\nMay\nJun\nJul\nAug"

cat("Here are the days: ", days)
cat("Here are the months: ", months)

cat(
  "There's something going on here.\n",
  "With the three double-quotes.\n",
  "We'll be able to type as much as we like.\n",
  "Even 4 lines if we want, or 5, or 6."
)
```
