---
title: "ex7"
author: "Robert A. Stevens"
date: "July 9, 2014"
output: html_document
---

http://learnpythonthehardway.org/book/ex7.html

Exercise 7: More Printing

Python code

```{r, engine='python'}
print "Mary had a little lamb."
print "Its fleece was white as %s." % 'snow'
print "And everywhere that Mary went."
print "." * 10  # what'd that do?

end1 = "C"
end2 = "h"
end3 = "e"
end4 = "e"
end5 = "s"
end6 = "e"
end7 = "B"
end8 = "u"
end9 = "r"
end10 = "g"
end11 = "e"
end12 = "r"

# watch that comma at the end.  try removing it to see what happens
print end1 + end2 + end3 + end4 + end5 + end6,
print end7 + end8 + end9 + end10 + end11 + end12
```

R code

```{r}
print("Mary had a little lamb.")
sprintf("Its fleece was white as %s.", "snow")
print("And everywhere that Mary went.")
cat(rep(".", 10), sep = "") # what'd that do?

end1 <- "C"
end2 <- "h"
end3 <- "e"
end4 <- "e"
end5 <- "s"
end6 <- "e"
end7 <- "B"
end8 <- "u"
end9 <- "r"
end10 <- "g"
end11 <- "e"
end12 <- "r"

# watch that comma at the end.  try removing it to see what happens
print(paste(end1, end2, end3, end4, end5, end6, " ",
            end7, end8, end9, end10, end11, end12, sep = ""))
```
